name: Hadi polivka
favicon: null
layout_spectrum: 0.91654
typography_spectrum: 0.10743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dff5e0'
    - '#120a07'
    - '#634d26'
    - '#8b8c4a'
    - '#5fd9d9'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
